name: Build Multiplatform project
on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'
jobs:
  build-multiplatform-project:
    if: github.event.pull_request.merged == true
    environment: release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: ./gradlew lib:publishAllPublicationsToMavenCentralRepository
